WebApplication/Models/CostCenter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication.Models
{
    public class CostCenter
    {
        [Key]
        public int ID { get; set; }

        [Display(Name = "Cost Center")]
        [Required(ErrorMessage = "Cost Center is required")]
        public string Description { get; set; }

        
        public virtual ICollection<PurchaseRequest> PurchaseRequests { get; set; }
    }
}

WebApplication/Controllers/CostCentersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.DAL;
using WebApplication.Models;
using WebApplication.Common;

namespace WebApplication.Controllers
{
    public class CostCentersController : Controller
    {
        private SupplyOfficeContext db = new SupplyOfficeContext();


        [AjaxOnly]
        public PartialViewResult GetList()
        {
            return PartialView("_costcentersList", db.CostCenters.ToList());
        }
        // GET: CostCenters
        public ActionResult Index()
        {
            return View();
        }

        // GET: CostCenters/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CostCenter costCenter = await db.CostCenters.FindAsync(id);
            if (costCenter == null)
            {
                return HttpNotFound();
            }
            return View(costCenter);
        }

        // GET: CostCenters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CostCenters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Description")] CostCenter costCenter)
        {
            if (ModelState.IsValid)
            {
                db.CostCenters.Add(costCenter);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(costCenter);
        }

        // GET: CostCenters/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CostCenter costCenter = await db.CostCenters.FindAsync(id);
            if (costCenter == null)
            {
                return HttpNotFound();
            }
            return View(costCenter);
        }

        // POST: CostCenters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Description")] CostCenter costCenter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(costCenter).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(costCenter);
        }

        // GET: CostCenters/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CostCenter costCenter = await db.CostCenters.FindAsync(id);
            if (costCenter == null)
            {
                return HttpNotFound();
            }
            return View(costCenter);
        }

        // POST: CostCenters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CostCenter costCenter = await db.CostCenters.FindAsync(id);
            db.CostCenters.Remove(costCenter);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/CostCenters/Create.cshtml
@model WebApplication.Models.CostCenter

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CostCenter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/CostCenters/Delete.cshtml
@model WebApplication.Models.CostCenter

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CostCenter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication/Views/CostCenters/Details.cshtml
@model WebApplication.Models.CostCenter

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CostCenter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication/Views/CostCenters/Edit.cshtml
@model WebApplication.Models.CostCenter

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CostCenter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/CostCenters/Index.cshtml
@model WebApplication.Models.CostCenter
@{
    ViewBag.Title = "Cost Centers";
    ViewBag.SubTitle = "Sections";

}
@section Menu {

    <script type="text/javascript">
        var menuItem = $('#left-sidebar-menu-p6m');
        menuItem.addClass('active');
        var subMenuItem = menuItem.find('#left-sidebar-menu-p6m-costcenter');
        subMenuItem.addClass('active');

        $(document).ajaxStart(function () {
            $("#loading").show();
        });

        $(document).ajaxComplete(function () {
            $("#loading").hide();
        });


    </script>
}

@Styles.Render("~/Content/plugins/datatables/css")

<div class="row">
    <div class="col-xs-8" id="costcenter_list">
        <div class="col-xs-12 text-center" id="loading">
            <button type="button" class="btn btn-default btn-lrg ajax" title="Ajax Request">
                <i class="fa fa-spin fa-refresh"></i>&nbsp; Loading content...
            </button>
        </div>
    </div>



    <div class="col-xs-4">
        <div class="box box-success box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Add Cost Center</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="">
                @using (Html.BeginForm("Create", "CostCenters", FormMethod.Post, new { id = "form_add_unit" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-2">Description</label>

                            <div class="col-md-12">
                                <textarea class = "form-control" rows="4" name = "Description" placeholder = "Cost center description"></textarea>
                                
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }
            </div>
            <!-- /.box-body -->
        </div>
    </div>


</div>

@section Scripts {
    @Scripts.Render("~/Content/plugins/datatables/js")
    @Scripts.Render("~/Scripts/jquery-validate/js")

    <script type="text/javascript">
        $(function () {

            $.ajax({
                url: '/CostCenters/GetList',
                dataType: 'html',
                success: function (data) {

                    $('#costcenter_list').html(data);

                    var table = $('#units-all').DataTable({
                        drawCallback: function () {
                            $('[data-toggle=confirmation]').confirmation({
                                rootSelector: '[data-toggle=confirmation]',
                                // other options
                            });
                        }
                    });

                }
            });


            $("#form_add_unit").validate({
                errorElement: "span",
                errorClass: "help-block text-red",
                submitHandler: function (vform) {
                    vform.submit();
                },
                rules: {
                    Description: {
                        required: true,
                        minlength: 2
                    }
                },
                messages: {
                    Description: {
                        required: "Not submitted! Text field cannot be empty.",
                        minlength: jQuery.validator.format("At least {0} characters required!")
                    }
                }
            });


        });
    </script>
}

WebApplication/Views/CostCenters/_costcentersList.cshtml
@model IEnumerable<WebApplication.Models.CostCenter>


<div class="box box-primary box-solid">
    <div class="box-header with-border">
        <h3 class="box-title">List of all recorder Cost Center</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <table id="units-all" class="table table-bordered table-hover">
            <thead>
                <tr>
                    
                    <th>@Html.DisplayNameFor(model => model.Description) </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @using (Html.BeginForm("Edit", "CostCenters", new { id = item.ID }, FormMethod.Post, new { id = $"update_costcenter_{@item.ID}", @class = "form-group" }))
                            {
                                @Html.AntiForgeryToken()
                                <a class="badge bg-yellow"
                                    data-toggle="confirmation"
                                    title="Editing Cost Center"
                                    data-html="true"
                                    data-placement="top"
                                    data-singleton="true"
                                    data-popout="true"
                                    data-btn-ok-label="Update" data-btn-ok-icon="fa fa-fw fa-thumbs-o-up"
                                    data-btn-cancel-label="Cancel" data-btn-cancel-icon="fa fa-fw fa-thumbs-o-down"
                                    data-content="
                                    <div class='form-group'>
                                        <label class='control-label col-md-1'>Description</label>

                                        <div class='col-md-12'>
                                           <textarea name='Description' row='4' id='Description' class='form-control'> @item.Description </textarea>
                                        </div>
                                    </div>
                                            "
                                    href="javascript:document.getElementById('update_costcenter_@item.ID').submit()">Edit</a>
                            }

                          
                            
                            @using (Html.BeginForm("Delete", "CostCenters", new { id = item.ID }, FormMethod.Post, new { id = $"delete_costcenter_{@item.ID}", @class = "form-group" }))
                            {
                                @Html.AntiForgeryToken()
                                <a class="badge bg-red"c
                                    data-toggle="confirmation"
                                    data-title="Remove @item.Description from record?"
                                    data-btn-ok-label="Yes" data-btn-ok-icon="fa fa-fw fa-thumbs-o-up"
                                    data-btn-cancel-label="No" data-btn-cancel-icon="fa fa-fw fa-thumbs-o-down"
                                    data-singleton="true"
                                    data-popout="true"
                                    href="javascript:document.getElementById('delete_costcenter_@item.ID').submit()">Remove</a>
                             }                                                   
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>