WebApplication/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.DAL;
using WebApplication.Models;
using WebApplication.Common;

namespace WebApplication.Controllers
{
    public class StocksController : Controller
    {
        private SupplyOfficeContext db = new SupplyOfficeContext();

        // GET: Stocks
        [AjaxOnly]
        public PartialViewResult GetList()
        {
            ViewBag.Units = db.Units.ToList();
            return PartialView("_unitsListStocks", db.Stocks.ToList());
        }

        // GET: Stocks
        public ActionResult Index()
        {
  
            ViewBag.UnitID = new SelectList(db.Units, "ID", "UnitName");
            return View();
        }


        //override
       
        public void UpdateContent()
        {
            List<Stock> stocks = db.Stocks.ToList();
            List<Stock> updateStocks = new List<Stock>();


            foreach (Stock s in stocks)
            {
                var description = s.Description;
                var descriptionArray = description.Split(',');
                var name = descriptionArray?[0] ?? description.ToUpper();

                if (!ReferenceEquals(descriptionArray[0], null))
                {
                    description = String.Join(", ", descriptionArray, 1, descriptionArray.Length - 1);
                }

                var stockNumberPrefix = "";


                
                //for stock number
                stockNumberPrefix = CleanString(name);
                   

                var stockCount = updateStocks.Where(c => c.Name == name)?.Count();
                stockCount++;

                var stockNumber = stockNumberPrefix + "-" + stockCount;

                Stock _stock = db.Stocks.Find(s.ID);
                _stock.StockNumber = stockNumber.Trim();
                _stock.Name = name.Trim();
                _stock.Description = description.Trim();
         

                updateStocks.Add(_stock);

                if (ModelState.IsValid)
                {
                    db.Entry(_stock).State = EntityState.Modified;

                    db.SaveChanges();

                }
                else
                {
                    Console.Write("ambot!");
                }
                
            }
            
        }


        protected string CleanString(string n)
        {
            if (n != null || n != "")
            {
                if (n.Length <= 4)
                {
                    //for stock number
                    return n.ToUpper();
                }
                else
                {
                    string vowels = "aeiouy";
                    string name = n.ToLower();

                    name = new string(name.Where(c => !vowels.Contains(c)).ToArray());
                    name = name.Replace(" ", "");

                    if (name.Length < 3)
                    {
                        name = n.Replace(" ", "");
                    }

                    return name?.Substring(0, Math.Min(4, name.Length - 1))?.ToUpper() ?? "";

                }
            }

            return null;
            
        }

        // GET: Stocks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stock stock = await db.Stocks.FindAsync(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            return View(stock);
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<int> Create([Bind(Include = "ID,Name,Description,UnitID")] Stock stock)
        {
            if (ModelState.IsValid)
            {
                var _stockName = stock.Name;
                var stockCount = db.Stocks.Where(c => c.Name.ToUpper().Trim().Equals(_stockName.ToUpper().Trim())).Count();
                var count = ++stockCount;

                stock.StockNumber = CleanString(_stockName) + "-" + count;

                db.Stocks.Add(stock);
                return await db.SaveChangesAsync();
                
            }

            ViewBag.UnitID = new SelectList(db.Units, "ID", "UnitName", stock.UnitID);
            return 0;
        }


        // POST: Stocks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,StockNumber,Name,Description,UnitID")] Stock stock)
        {
            if (ModelState.IsValid)
            { 
                db.Entry(stock).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.UnitID = new SelectList(db.Units, "ID", "UnitName", stock.UnitID);
            return View(stock);
        }

        // GET: Stocks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stock stock = await db.Stocks.FindAsync(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            return View(stock);
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Stock stock = await db.Stocks.FindAsync(id);
            db.Stocks.Remove(stock);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Controllers/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.DAL;
using WebApplication.Models;
using WebApplication.Common;

namespace WebApplication.Controllers
{
    public class UnitsController : Controller
    {
        private SupplyOfficeContext db = new SupplyOfficeContext();

        [AjaxOnly]
        public PartialViewResult GetList()
        {
            return PartialView("_unitsList", db.Units.ToList());
        }

        // GET: Units
        public ActionResult Index()
        {
            return View();
        }

        // GET: Units/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = await db.Units.FindAsync(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // GET: Units/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,UnitName")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Units.Add(unit);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(unit);
        }

        // GET: Units/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = await db.Units.FindAsync(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,UnitName")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(unit).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(unit);
        }

        // GET: Units/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = await db.Units.FindAsync(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Unit unit = await db.Units.FindAsync(id);
            db.Units.Remove(unit);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
@using WebApplication.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Supply Office IS | MSU Naawan</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @Styles.Render("~/AdminLTE/plugins/font-awesome/css")
    @Styles.Render("~/AdminLTE/plugins/ionicons/css")
    @Styles.Render("~/AdminLTE/bootstrap/css")
    @Styles.Render("~/AdminLTE/dist/css")
    @Styles.Render("~/AdminLTE/dist/css/skins")

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="@Url.Action("DashboardV1", "Home")" class="logo">
                <span class="logo-mini"><b>So</b>iS</span>
                <span class="logo-lg"><b>Supply</b>Office</span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@User.Identity.GetUserNameIdentifier()</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li id="left-sidebar-menu-dataEntry" class="treeview">
                        <a href="#">
                            <i class="fa fa-fw fa-industry"></i>
                            <span>Data Entry</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li id="left-sidebar-menu-dataEntry-ris"><a href="@Url.Action("Index", "Requisitions")"><i class="fa fa-fw fa-minus-circle"></i> R.I.S.</a></li>
                            <li id="left-sidebar-menu-dataEntry-del"><a href="@Url.Action("Index", "Deliveries")"><i class="fa fa-fw fa-plus-circle"></i> Manage Delivery</a></li>
                            <li id="left-sidebar-menu-dataEntry-po"><a href="@Url.Action("Index", "PurchaseOrders")"><i class="fa fa-fw fa-book"></i> Manage P.O.</a></li>
                            <li id="left-sidebar-menu-dataEntry-pr"><a href="@Url.Action("Index", "PurchaseRequests")"><i class="fa fa-fw fa-book"></i> Manage P.R.</a></li>
                            <li id="left-sidebar-menu-dataEntry-stocks"><a href="@Url.Action("Index", "Stocks")"><i class="fa fa-fw fa-pencil-square"></i> Add/Update Stocks</a></li>
                            <li id="left-sidebar-menu-dataEntry-unit"><a href="@Url.Action("Index", "Units")"><i class="fa fa-fw fa-list-alt"></i> Manage Stock Units</a></li>
                            <li id="left-sidebar-menu-dataEntry-costcenter"><a href="@Url.Action("Index", "CostCenters")"><i class="fa fa-fw fa-list-alt"></i> Manage Cost Centers</a></li>
                        </ul>
                    </li>
                    <li id="left-sidebar-menu-supply" class="treeview">
                        <a href="#">
                            <i class="fa fa-th"></i> 
                            <span>Reports</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li id="left-sidebar-menu-report-stockCard"><a href="#"><i class="fa fa-circle-o"></i> Stock Card</a></li>
                        </ul>
                    </li>

                    <li class="header">Supply Office | Information System</li>
                    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
                    <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
                    <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
                </ul>
            </section>
        </aside>
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.SubTitle</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i>@ViewBag.SubTitle</a></li>
                    <li class="active">@ViewBag.Title</li>
                </ol>
            </section>
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.0b
            </div>
            <strong>MINDANAO STATE UNIVERSITY | Naawan &copy; 2017 <a href="#">IT Services</a>.</strong> JLunas
        </footer>
    </div>

    @Scripts.Render("~/Scripts/jquery/js")
    @RenderSection("menu", required: false)
    @Scripts.Render("~/AdminLTE/bootstrap/js")
    @Scripts.Render("~/Content/plugins/bootstrap-confirmation/js")
    @Scripts.Render("~/AdminLTE/plugins/slimscroll/js")
    @Scripts.Render("~/AdminLTE/plugins/fastclick/js")
    @Scripts.Render("~/Scripts/Shared/_Layout")
    @Scripts.Render("~/AdminLTE/dist/js")
    @Scripts.Render("~/Scripts/Shared/Custom")
    @RenderSection("scripts", required: false)
</body>
</html>